FROM node:20.10.0-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
ADD patches ./patches

# Install dependencies
RUN npm install
RUN npx patch-package

# Copy source code
COPY . .

# Expose Vite dev server port
EXPOSE 3000

# Start Vite dev server
CMD ["npm", "run", "dev", "--", "0.0.0.0"]