export const regions = {
  AT: { name: "Austria", currency: "EUR", tax: 20 },
  AU: { name: "Australia", currency: "AUD", tax: 10 },
  BD: { name: "Bangladesh", currency: "BDT", tax: 15 },
  BE: { name: "Belgium", currency: "EUR", tax: 21 },
  BG: { name: "Bulgaria", currency: "BGN", tax: 20 },
  BH: { name: "Bahrain", currency: "USD", tax: 10 },
  BM: { name: "Bermuda", currency: "USD", tax: 0 },
  BO: { name: "Bolivia", currency: "BOB", tax: 0 },
  BR: { name: "Brazil", currency: "BRL", tax: 0 },
  CA: { name: "Canada", currency: "CAD", tax: 0 },
  CH: { name: "Switzerland", currency: "CHF", tax: 0 },
  CL: { name: "Chile", currency: "CLP", tax: 19 },
  CO: { name: "Colombia", currency: "COP", tax: 0 },
  CR: { name: "Costa Rica", currency: "CRC", tax: 0 },
  CY: { name: "Cyprus", currency: "EUR", tax: 19 },
  CZ: { name: "Czech Republic", currency: "CZK", tax: 21 },
  DE: { name: "Germany", currency: "EUR", tax: 19 },
  DK: {
    name: "Denmark",
    currency: "DKK",
    tax: 25,
    subregions: { GL: { tax: 0 }, FO: { tax: 0 } },
  },
  DZ: { name: "Algeria", currency: "DZD", tax: 0 },
  EC: { name: "Ecuador", currency: "USD", tax: 0 },
  EE: { name: "Estonia", currency: "EUR", tax: 22 },
  EG: { name: "Egypt", currency: "EGP", tax: 14 },
  ES: {
    name: "Spain",
    currency: "EUR",
    tax: 21,
    subregions: {
      "ES-LAS PALMAS": { tax: 7 },
      "ES-MELILLA": { tax: 0.5 },
      "ES-CEUTA": { tax: 0.5 },
      "ES-SANTA CRUZ DE TENERIFE": { tax: 7 },
    },
  },
  FI: {
    name: "Finland",
    currency: "EUR",
    tax: 24,
    subregions: { AX: { tax: 24 } },
  },
  FM: { name: "Micronesia", currency: "USD", tax: 0 },
  FR: {
    name: "France",
    currency: "EUR",
    tax: 20,
    subregions: {
      BL: { tax: 0 },
      GF: { tax: 0 },
      GP: { tax: 8.5 },
      MF: { tax: 0 },
      MQ: { tax: 8.5 },
      NC: { tax: 0 },
      PF: { tax: 0 },
      PM: { tax: 0 },
      RE: { tax: 8.5 },
      WF: { tax: 0 },
      YT: { tax: 0 },
    },
  },
  GE: { name: "Georgia", currency: "GEL", tax: 18 },
  GH: { name: "Ghana", currency: "GHS", tax: 21.9 },
  GI: { name: "Gibraltar", currency: "GBP", tax: 0 },
  GR: { name: "Greece", currency: "EUR", tax: 24 },
  HK: { name: "Hong Kong", currency: "HKD", tax: 0 },
  HR: { name: "Croatia", currency: "EUR", tax: 25 },
  HU: { name: "Hungary", currency: "HUF", tax: 27 },
  ID: { name: "Indonesia", currency: "IDR", tax: 0 },
  IE: { name: "Ireland", currency: "EUR", tax: 23 },
  IL: { name: "Israel", currency: "ILS", tax: 0 },
  IN: { name: "India", currency: "INR", tax: 18 },
  IQ: { name: "Iraq", currency: "IQD", tax: 0 },
  IT: { name: "Italy", currency: "EUR", tax: 22 },
  JO: { name: "Jordan", currency: "JOD", tax: 0 },
  JP: { name: "Japan", currency: "JPY", tax: 0 },
  KE: { name: "Kenya", currency: "KES", tax: 16 },
  KH: { name: "Cambodia", currency: "USD", tax: 0 },
  KR: { name: "South Korea", currency: "KRW", tax: 10 },
  KW: { name: "Kuwait", currency: "USD", tax: 0 },
  KY: { name: "Cayman Islands", currency: "USD", tax: 0 },
  KZ: { name: "Kazakhstan", currency: "KZT", tax: 12 },
  LI: { name: "Liechtenstein", currency: "CHF", tax: 8.1 },
  LK: { name: "Sri Lanka", currency: "LKR", tax: 0 },
  LT: { name: "Lithuania", currency: "EUR", tax: 21 },
  LU: { name: "Luxembourg", currency: "EUR", tax: 17 },
  LV: { name: "Latvia", currency: "EUR", tax: 21 },
  MA: { name: "Morocco", currency: "MAD", tax: 20 },
  MC: { name: "Monaco", currency: "EUR", tax: 20 },
  MM: { name: "Myanmar", currency: "MMK", tax: 0 },
  MO: { name: "Macao", currency: "MOP", tax: 0 },
  MX: { name: "Mexico", currency: "MXN", tax: 16 },
  MY: { name: "Malaysia", currency: "MYR", tax: 8 },
  NG: { name: "Nigeria", currency: "NGN", tax: 7.5 },
  NL: { name: "Netherlands", currency: "EUR", tax: 21 },
  NO: {
    name: "Norway",
    currency: "NOK",
    tax: 25,
    subregions: { SJ: { tax: 0 } },
  },
  NZ: { name: "New Zealand", currency: "NZD", tax: 15 },
  OM: { name: "Oman", currency: "USD", tax: 5 },
  PA: { name: "Panama", currency: "USD", tax: 0 },
  PE: { name: "Peru", currency: "PEN", tax: 0 },
  PH: { name: "Philippines", currency: "PHP", tax: 0 },
  PK: { name: "Pakistan", currency: "PKR", tax: 0 },
  PL: { name: "Poland", currency: "PLN", tax: 23 },
  PT: { name: "Portugal", currency: "EUR", tax: 23 },
  RO: { name: "Romania", currency: "RON", tax: 19 },
  QA: { name: "Qatar", currency: "QAR", tax: 0 },
  RU: { name: "Russia", currency: "RUB", tax: 0 },
  SV: { name: "Salvador", currency: "USD", tax: 0 },
  SM: { name: "San Marino", currency: "EUR", tax: 0 },
  SA: { name: "Saudi Arabia", currency: "SAR", tax: 15 },
  RS: { name: "Serbia", currency: "RSD", tax: 20 },
  SG: { name: "Singapore", currency: "SGD", tax: 9 },
  SK: { name: "Slovakia", currency: "EUR", tax: 20 },
  SI: { name: "Slovenia", currency: "EUR", tax: 22 },
  ZA: { name: "South Africa", currency: "ZAR", tax: 15 },
  SE: { name: "Sweden", currency: "SEK", tax: 25 },
  TW: { name: "Taiwan", currency: "TWD", tax: 5 },
  TZ: { name: "Tanzania", currency: "TZS", tax: 0 },
  TH: { name: "Thailand", currency: "THB", tax: 7 },
  TC: { name: "Turks & Caicos Islands", currency: "USD", tax: 0 },
  TR: { name: "Türkiye", currency: "TRY", tax: 20 },
  UA: { name: "Ukraine", currency: "UAH", tax: 20 },
  AE: { name: "United Arab Emirates", currency: "AED", tax: 5 },
  GB: { name: "United Kingdom", currency: "GBP", tax: 20 },
  US: {
    name: "United States",
    currency: "USD",
    tax: 0,
    subregions: {
      AS: { tax: 0 },
      GU: { tax: 0 },
      MH: { tax: 0 },
      MP: { tax: 0 },
      PR: { tax: 0 },
      PW: { tax: 0 },
      VI: { tax: 0 },
    },
  },
  // VA: { name: "Vatican City", currency: "EUR", tax: 0 },
  VN: { name: "Vietnam", currency: "VND", tax: 0 },
};
