const languages = [
  // Put top languages first
  { code: "en", name: "English", flag: "US", englishName: "English" },
  {
    code: "fr-FR",
    name: "Français (France)",
    flag: "FR",
    englishName: "French",
  },
  { code: "it", name: "Italiano", flag: "IT", englishName: "Italian" },
  { code: "de", name: "Deutsch", flag: "DE", englishName: "German" },
  {
    code: "zh",
    name: "中文（简体）",
    flag: "CN",
    englishName: "Chinese (Simplified)",
  },
  {
    code: "es",
    name: "Español (España)",
    flag: "ES",
    englishName: "Spanish (Spain)",
  },
  { code: "pl", name: "Polski", flag: "PL", englishName: "Polish" },
  { code: "da", name: "Dansk", flag: "DK", englishName: "Danish" },
  { code: "lv", name: "Latviešu", flag: "LV", englishName: "Latvian" },
  { code: "et", name: "Eesti", flag: "EE", englishName: "Estonian" },
  { code: "hi", name: "हिन्दी", flag: "IN", englishName: "Hindi" },
  { code: "ja", name: "日本語", flag: "JP", englishName: "Japanese" },
  { code: "nl", name: "Nederlands", flag: "NL", englishName: "Dutch" },
  { code: "bg", name: "", flag: "BG", englishName: "Bulgarian" },
  { code: "no", name: "Norsk", flag: "NO", englishName: "Norwegian" },
  { code: "sv", name: "Svenska", flag: "SE", englishName: "Swedish" },
  { code: "tr", name: "Türkçe", flag: "TR", englishName: "Turkish" },

  { code: "af", name: "Afrikaans", flag: "ZA", englishName: "Afrikaans" },
  { code: "sq", name: "Shqip", flag: "AL", englishName: "Albanian" },
  { code: "am", name: "አማርኛ", flag: "ET", englishName: "Amharic" },
  {
    code: "en-AU",
    name: "English (Australia)",
    flag: "AU",
    englishName: "English",
  },
  {
    code: "en-CA",
    name: "English (Canada)",
    flag: "CA",
    englishName: "English",
  },
  {
    code: "en-GB",
    name: "English (United Kingdom)",
    flag: "GB",
    englishName: "English",
  },
  { code: "ar", name: "العربية", flag: "SA", englishName: "Arabic" },
  { code: "hy", name: "Հայերեն", flag: "AM", englishName: "Armenian" },
  { code: "my", name: "ဗမာ", flag: "MM", englishName: "Burmese" },
  { code: "eu", name: "Euskara", flag: "ES", englishName: "Basque" },
  { code: "bn", name: "বাংলা", flag: "BD", englishName: "Bengali" },
  { code: "be", name: "", flag: "BY", englishName: "Belarusian" },
  { code: "hr", name: "Hrvatski", flag: "HR", englishName: "Croatian" },
  { code: "tl", name: "Filipino", flag: "PH", englishName: "Filipino" },
  { code: "fi", name: "Suomi", flag: "FI", englishName: "Finnish" },
  { code: "gl", name: "Galego", flag: "ES", englishName: "Galician" },
  {
    code: "fr-CA",
    name: "Français (Canada)",
    flag: "CA",
    englishName: "French",
  },
  { code: "ka", name: "ქართული", flag: "GE", englishName: "Georgian" },
  { code: "gu", name: "ગુજરાતી", flag: "IN", englishName: "Gujarati" },
  { code: "he", name: "עברית", flag: "IL", englishName: "Hebrew" },
  { code: "id", name: "Indonesia", flag: "ID", englishName: "Indonesian" },
  { code: "is", name: "Íslenska", flag: "IS", englishName: "Icelandic" },
  { code: "kn", name: "ಕನ್ನಡ", flag: "IN", englishName: "Kannada" },
  { code: "ca", name: "Català", flag: "ES", englishName: "Catalan" },
  { code: "kk", name: "Ққ іі", flag: "KZ", englishName: "Kazakh" },
  { code: "km", name: "ខ្មែរ", flag: "KH", englishName: "Khmer" },
  { code: "ko", name: "한국어", flag: "KR", englishName: "Korean" },
  { code: "ky", name: "", flag: "KG", englishName: "Kyrgyz" },
  { code: "lo", name: "ລາວ", flag: "LA", englishName: "Lao" },
  { code: "lt", name: "Lietuvių", flag: "LT", englishName: "Lithuanian" },
  { code: "mk", name: "", flag: "MK", englishName: "Macedonian" },
  { code: "ml", name: "മലയാളം", flag: "IN", englishName: "Malayalam" },
  {
    code: "ms-MY",
    name: "Bahasa Melayu (Malaysia)",
    flag: "MY",
    englishName: "Malay (Malaysia)",
  },
  { code: "ms", name: "Bahasa Melayu", flag: "MY", englishName: "Malay" },
  { code: "mr", name: "मराठी", flag: "IN", englishName: "Marathi" },
  { code: "hu", name: "Magyar", flag: "HU", englishName: "Hungarian" },
  { code: "mn", name: "", flag: "MN", englishName: "Mongolian" },
  { code: "ne", name: "नेपाली", flag: "NP", englishName: "Nepali" },
  { code: "pa", name: "ਪੰਜਾਬੀ", flag: "IN", englishName: "Punjabi" },
  { code: "fa", name: "فارسی", flag: "IR", englishName: "Persian" },
  {
    code: "pt-BR",
    name: "Português (Brasil)",
    flag: "BR",
    englishName: "Portuguese (Brazil)",
  },
  {
    code: "pt-PT",
    name: "Português (Portugal)",
    flag: "PT",
    englishName: "Portuguese (Portugal)",
  },
  { code: "ro", name: "Română", flag: "RO", englishName: "Romanian" },
  { code: "ru", name: "", flag: "RU", englishName: "Russian" },
  { code: "rm", name: "Rumantsch", flag: "CH", englishName: "Romansh" },
  { code: "si", name: "සිංහල", flag: "LK", englishName: "Sinhala" },
  { code: "sk", name: "Slovenčina", flag: "SK", englishName: "Slovak" },
  { code: "sl", name: "Slovenščina", flag: "SI", englishName: "Slovenian" },
  { code: "sr", name: "", flag: "RS", englishName: "Serbian" },
  { code: "sw", name: "Kiswahili", flag: "TZ", englishName: "Swahili" },
  { code: "ta", name: "தமிழ்", flag: "IN", englishName: "Tamil" },
  { code: "te", name: "తెలుగు", flag: "IN", englishName: "Telugu" },
  { code: "th", name: "ไทย", flag: "TH", englishName: "Thai" },
  { code: "uk", name: "ї", flag: "UA", englishName: "Ukrainian" },
  { code: "ur", name: "اردو", flag: "PK", englishName: "Urdu" },
  { code: "vi", name: "Tiếng Việt", flag: "VN", englishName: "Vietnamese" },
  { code: "zu", name: "Zulu", flag: "ZA", englishName: "Zulu" },
  {
    code: "az",
    name: "Azərbaycan dili",
    flag: "AZ",
    englishName: "Azerbaijani",
  },
  { code: "cs", name: "Čeština", flag: "CZ", englishName: "Czech" },
  {
    code: "zh-HK",
    name: "中文（香港）",
    flag: "HK",
    englishName: "Chinese (Hong Kong)",
  },
  {
    code: "zh-TW",
    name: "中文（繁體）",
    flag: "TW",
    englishName: "Chinese (Traditional)",
  },
  { code: "el", name: "Ελληνικά", flag: "GR", englishName: "Greek" },
  {
    code: "es-419",
    name: "Español (Latinoamérica)",
    flag: "WL",
    englishName: "Spanish (Latin America)",
  },
  {
    code: "es-US",
    name: "Español (Estados Unidos)",
    flag: "US",
    englishName: "Spanish (United States)",
  },
];

export default languages;
